version: '2'
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../jupyterhub-deploy-docker-localhost/secrets:/etc/nginx/certs"

networks:
  default:
    external:
      name: jupyterhub-network
